### ISSUE TITLE
Add the CAM02-UCS color space

### ISSUE THREAD

**Issue by MisterSheik** [gtaylor/python-colormath#55]
Please consider adding the CAM02-UCS color space, which is described here: https://www.youtube.com/watch?v=xAoljeRJ3lU

**Comment by gtaylor** [comment]
I don't have the bandwidth to tackle this personally, but I certainly would be interested in seeing a pull request.

Since this isn't immediately actionable, I'm going to close this for now. If you do end up wanting to head up the effort, I'll make time to provide advice and/or reviews as necessary.
